### ISSUE TITLE
How to use 

### ISSUE THREAD

**Issue by xseries55301** [LG125YT/discord-websocket-connection#1]
How do I use this?

**Comment by LG125YT** [comment]
The README should be self explanatory, but basically all that you need to get is your application token from https://hummus.sys42.net/developers/applications/me and add commands. You can add commands under the `check()` function, just look at any other command for an example on how to do so.

If it’s still a little confusing, don’t worry. I’m working on an API wrapper for Hummus. You can see it’s current development [here on the GitLab](https://gitlab.com/lg125yt/hummus.py)

**Comment by xseries55301** [comment]
Ok thank you.
